// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/login" | "/auth/signup" | "/cms/shops/[shopId]" | "/cms/shops/[shopId]/edit" | "/cms/shops/[shopId]/items/[itemId]/edit" | "/cms/shops/[shopId]/items/new" | "/cms/shops/[shopId]/settings" | "/items/[itemId]" | "/my" | "/my/following/shops" | "/my/following/users" | "/my/keep" | "/my/keep/[folderId]" | "/my/profile" | "/search" | "/shop" | "/shop/create" | "/shops/[shopId]" | "/users/[userId]"
type AppRouteHandlerRoutes = "/api/shops/[shopId]/settings" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/shops/[shopId]/settings": { "shopId": string; }
  "/auth/callback": {}
  "/auth/login": {}
  "/auth/signup": {}
  "/cms/shops/[shopId]": { "shopId": string; }
  "/cms/shops/[shopId]/edit": { "shopId": string; }
  "/cms/shops/[shopId]/items/[itemId]/edit": { "shopId": string; "itemId": string; }
  "/cms/shops/[shopId]/items/new": { "shopId": string; }
  "/cms/shops/[shopId]/settings": { "shopId": string; }
  "/items/[itemId]": { "itemId": string; }
  "/my": {}
  "/my/following/shops": {}
  "/my/following/users": {}
  "/my/keep": {}
  "/my/keep/[folderId]": { "folderId": string; }
  "/my/profile": {}
  "/search": {}
  "/shop": {}
  "/shop/create": {}
  "/shops/[shopId]": { "shopId": string; }
  "/users/[userId]": { "userId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
