// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../../app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cms/shops/[shopId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cms/shops/[shopId]/edit">> = Specific
  const handler = {} as typeof import("../../../app/cms/shops/[shopId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cms/shops/[shopId]/items/[itemId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cms/shops/[shopId]/items/[itemId]/edit">> = Specific
  const handler = {} as typeof import("../../../app/cms/shops/[shopId]/items/[itemId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cms/shops/[shopId]/items/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cms/shops/[shopId]/items/new">> = Specific
  const handler = {} as typeof import("../../../app/cms/shops/[shopId]/items/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cms/shops/[shopId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cms/shops/[shopId]">> = Specific
  const handler = {} as typeof import("../../../app/cms/shops/[shopId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cms/shops/[shopId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cms/shops/[shopId]/settings">> = Specific
  const handler = {} as typeof import("../../../app/cms/shops/[shopId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/items/[itemId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/items/[itemId]">> = Specific
  const handler = {} as typeof import("../../../app/items/[itemId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/following/shops/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/following/shops">> = Specific
  const handler = {} as typeof import("../../../app/my/following/shops/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/following/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/following/users">> = Specific
  const handler = {} as typeof import("../../../app/my/following/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/keep/[folderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/keep/[folderId]">> = Specific
  const handler = {} as typeof import("../../../app/my/keep/[folderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/keep/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/keep">> = Specific
  const handler = {} as typeof import("../../../app/my/keep/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my">> = Specific
  const handler = {} as typeof import("../../../app/my/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/profile">> = Specific
  const handler = {} as typeof import("../../../app/my/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shop/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/create">> = Specific
  const handler = {} as typeof import("../../../app/shop/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../../app/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shops/[shopId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shops/[shopId]">> = Specific
  const handler = {} as typeof import("../../../app/shops/[shopId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/users/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/[userId]">> = Specific
  const handler = {} as typeof import("../../../app/users/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/shops/[shopId]/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shops/[shopId]/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/shops/[shopId]/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
